-- 装斗记录表
CREATE TABLE IF NOT EXISTS herb_fill_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    record_no VARCHAR(30) NOT NULL COMMENT '编号 ZD+时间戳+序号',
    stock_in_id BIGINT COMMENT '关联入库单ID',
    drug_id BIGINT NOT NULL COMMENT '药品ID',
    drug_name VARCHAR(100) COMMENT '药品名称(快照)',
    specification VARCHAR(100) COMMENT '规格',
    unit VARCHAR(20) COMMENT '单位',
    batch_no VARCHAR(50) COMMENT '批号',
    fill_quantity DECIMAL(10,2) COMMENT '装斗数量',
    fill_date DATE COMMENT '装斗日期',
    origin VARCHAR(100) COMMENT '产地',
    manufacturer VARCHAR(200) COMMENT '生产企业',
    supplier_name VARCHAR(200) COMMENT '购进企业(供应商快照)',
    quality_status VARCHAR(20) NOT NULL DEFAULT '合格' COMMENT '质量状况(合格/不合格)',
    acceptance_result VARCHAR(20) NOT NULL DEFAULT '合格' COMMENT '验收结论(合格/不合格)',
    fill_person VARCHAR(50) COMMENT '装斗人',
    reviewer VARCHAR(50) DEFAULT '执业药师' COMMENT '复核人',
    created_by BIGINT,
    created_at DATETIME,
    updated_by BIGINT,
    updated_at DATETIME,
    deleted INT DEFAULT 0,
    INDEX idx_fill_date (fill_date),
    INDEX idx_stock_in_id (stock_in_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='装斗记录';

-- 清斗记录表
CREATE TABLE IF NOT EXISTS herb_clean_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    record_no VARCHAR(30) NOT NULL COMMENT '编号 QD+时间戳+序号',
    stock_in_id BIGINT COMMENT '关联入库单ID',
    drug_id BIGINT NOT NULL COMMENT '药品ID',
    drug_name VARCHAR(100) COMMENT '药品名称(快照)',
    specification VARCHAR(100) COMMENT '规格',
    unit VARCHAR(20) COMMENT '单位',
    batch_no VARCHAR(50) COMMENT '批号',
    remaining_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '剩余数量',
    clean_date DATE COMMENT '清斗日期',
    origin VARCHAR(100) COMMENT '产地',
    manufacturer VARCHAR(200) COMMENT '生产企业',
    review_status VARCHAR(20) NOT NULL DEFAULT '已复核' COMMENT '状态(已复核/未复核)',
    clean_person VARCHAR(50) COMMENT '清斗人',
    created_by BIGINT,
    created_at DATETIME,
    updated_by BIGINT,
    updated_at DATETIME,
    deleted INT DEFAULT 0,
    INDEX idx_clean_date (clean_date),
    INDEX idx_stock_in_id (stock_in_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='清斗记录';
