-- V5: 会员健康画像与慢病管理
-- 创建会员健康画像表
CREATE TABLE IF NOT EXISTS member_health_profile (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL COMMENT '会员ID',
    height DECIMAL(5,2) COMMENT '身高(cm)',
    weight DECIMAL(5,2) COMMENT '体重(kg)',
    bmi DECIMAL(4,1) COMMENT 'BMI指数',
    blood_type VARCHAR(10) COMMENT '血型',
    allergy_history TEXT COMMENT '过敏史JSON',
    family_history TEXT COMMENT '家族病史',
    surgery_history TEXT COMMENT '手术史',
    current_medications TEXT COMMENT '当前用药JSON',
    drinking_status VARCHAR(20) COMMENT '饮酒情况',
    smoking_status VARCHAR(20) COMMENT '吸烟情况',
    exercise_habit VARCHAR(20) COMMENT '运动习惯',
    sleep_quality VARCHAR(20) COMMENT '睡眠质量',
    health_tags TEXT COMMENT '健康标签JSON',
    last_update_date DATE COMMENT '最近更新日期',
    remark VARCHAR(500) COMMENT '备注',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    create_by BIGINT,
    update_by BIGINT,
    deleted TINYINT DEFAULT 0,
    INDEX idx_member_id (member_id),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员健康画像';

-- 创建慢病记录表
CREATE TABLE IF NOT EXISTS chronic_disease_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL COMMENT '会员ID',
    disease_type VARCHAR(50) NOT NULL COMMENT '疾病类型',
    disease_name VARCHAR(100) NOT NULL COMMENT '疾病名称',
    diagnosis_date DATE COMMENT '诊断日期',
    diagnosis_hospital VARCHAR(200) COMMENT '诊断医院',
    severity_level VARCHAR(20) COMMENT '病情等级',
    medication_plan TEXT COMMENT '用药方案JSON',
    target_indicators TEXT COMMENT '目标指标JSON',
    last_check_date DATE COMMENT '最近检查日期',
    last_check_result TEXT COMMENT '最近检查结果JSON',
    next_check_date DATE COMMENT '下次复查日期',
    management_status VARCHAR(20) DEFAULT 'active' COMMENT '管理状态',
    doctor_advice TEXT COMMENT '医嘱记录',
    remark VARCHAR(500) COMMENT '备注',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    create_by BIGINT,
    update_by BIGINT,
    deleted TINYINT DEFAULT 0,
    INDEX idx_member_id (member_id),
    INDEX idx_disease_type (disease_type),
    INDEX idx_next_check_date (next_check_date),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='慢病记录';

-- 创建用药提醒表
CREATE TABLE IF NOT EXISTS medication_reminder (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL COMMENT '会员ID',
    disease_record_id BIGINT COMMENT '关联慢病记录ID',
    drug_id BIGINT COMMENT '药品ID',
    drug_name VARCHAR(200) NOT NULL COMMENT '药品名称',
    specification VARCHAR(100) COMMENT '规格',
    dosage VARCHAR(50) COMMENT '单次用量',
    usage_method VARCHAR(20) COMMENT '用法',
    frequency VARCHAR(20) COMMENT '提醒频率',
    reminder_times TEXT COMMENT '提醒时间JSON',
    start_date DATE NOT NULL COMMENT '开始日期',
    end_date DATE COMMENT '结束日期',
    notify_method VARCHAR(20) DEFAULT 'sms' COMMENT '提醒方式',
    status VARCHAR(20) DEFAULT 'active' COMMENT '状态',
    precautions VARCHAR(500) COMMENT '注意事项',
    last_notify_date DATE COMMENT '最后提醒日期',
    remark VARCHAR(500) COMMENT '备注',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    create_by BIGINT,
    update_by BIGINT,
    deleted TINYINT DEFAULT 0,
    INDEX idx_member_id (member_id),
    INDEX idx_disease_record_id (disease_record_id),
    INDEX idx_status (status),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用药提醒';
