-- V6: GSP自动化与合规增强
-- 电子签名表
CREATE TABLE IF NOT EXISTS electronic_signature (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    business_type VARCHAR(50) NOT NULL COMMENT '业务类型',
    business_id BIGINT NOT NULL COMMENT '业务ID',
    signer_id BIGINT NOT NULL COMMENT '签名人ID',
    signer_name VARCHAR(50) COMMENT '签名人姓名',
    signer_position VARCHAR(50) COMMENT '签名人岗位',
    sign_time DATETIME NOT NULL COMMENT '签名时间',
    signature_data TEXT COMMENT '签名数据',
    verify_code VARCHAR(50) COMMENT '验证码',
    ip_address VARCHAR(50) COMMENT 'IP地址',
    operation_desc VARCHAR(500) COMMENT '操作说明',
    status VARCHAR(20) DEFAULT 'valid' COMMENT '状态',
    created_by BIGINT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT DEFAULT 0,
    INDEX idx_business (business_type, business_id),
    INDEX idx_signer (signer_id),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='电子签名';

-- GSP合规检查表
CREATE TABLE IF NOT EXISTS gsp_compliance_check (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    check_batch_no VARCHAR(50) NOT NULL COMMENT '检查批次号',
    store_id BIGINT NOT NULL COMMENT '门店ID',
    check_date DATE NOT NULL COMMENT '检查日期',
    check_type VARCHAR(20) NOT NULL COMMENT '检查类型',
    total_items INT DEFAULT 0 COMMENT '检查项目总数',
    passed_items INT DEFAULT 0 COMMENT '合格项数',
    failed_items INT DEFAULT 0 COMMENT '不合格项数',
    pass_rate INT DEFAULT 100 COMMENT '合格率',
    check_result TEXT COMMENT '检查结果JSON',
    issues TEXT COMMENT '问题描述',
    correction_measures TEXT COMMENT '整改措施',
    correction_deadline DATE COMMENT '整改期限',
    correction_status VARCHAR(20) DEFAULT 'pending' COMMENT '整改状态',
    checker_id BIGINT COMMENT '检查人ID',
    checker_name VARCHAR(50) COMMENT '检查人姓名',
    reviewer_id BIGINT COMMENT '审核人ID',
    reviewer_name VARCHAR(50) COMMENT '审核人姓名',
    review_date DATE COMMENT '审核时间',
    remark VARCHAR(500) COMMENT '备注',
    created_by BIGINT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT DEFAULT 0,
    INDEX idx_store_date (store_id, check_date),
    INDEX idx_check_type (check_type),
    INDEX idx_correction_status (correction_status),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='GSP合规检查';
